# ==================================================
# SSH
# ==================================================

USER=petr
HOST=10.0.1.21
PORT=22

# ==================================================
# Local
# ==================================================

LOCAL_FILE=target\iot-server-0.1.0-SNAPSHOT.jar

# ==================================================
# Remote
# ==================================================

UPLOAD_DIR=/home/petr/upload/
DEPLOY_SCRIPT=/home/petr/scripts/deploy.sh